config/routes.rb
Redump::Application.routes.draw do |map|
  resources :media_types

  resources :discs

end

app/models/disc.rb
class Disc < ActiveRecord::Base
  has_many :property_values
  belongs_to :media_type
  
  @@statuses = {
    1 => :not_dumped,
    2 => :dumped,
    3 => :redumped
  }
  
  def self.statuses
    @@statuses
  end
  
  attr_protected :created_at, :updated_at
  
  validates_inclusion_of :status, :in => @@statuses.keys
  validates_length_of :comments, :maximum => 65535
  validates_length_of :internal_serial, :maximum => 255
  validates_length_of :title, :in => 1..255
  validates_length_of :subtitle, :maximum => 255
  validates_length_of :scene_filename, :maximum => 255
  validates_length_of :filename, :maximum => 255
  validates_format_of :internal_date, :with => /\A(19|20)[0-9][0-9]-[01][0-9](-[0123][0-9])?\Z/, :allow_blank => true
  validates_format_of :size, :with => /\A[1-9][0-9]{6,13}\Z/, :allow_blank => true
  validates_format_of :crc32, :with => /\A[0-9A-Fa-f]{8}\Z/, :allow_blank => true
  validates_format_of :md5, :with => /\A[0-9A-Fa-f]{32}\Z/, :allow_blank => true
  validates_format_of :sha1, :with => /\A[0-9A-Fa-f]{40}\Z/, :allow_blank => true
  
  before_save do
    self.comments = self.comments.to_s
    self.internal_serial = self.internal_serial.to_s
    self.internal_date = self.internal_date.to_s
    self.subtitle = self.subtitle.to_s
    self.scene_filename = self.scene_filename.to_s
    self.filename = self.filename.to_s
    self.crc32 = self.crc32.to_s
    self.md5 = self.md5.to_s
    self.sha1 = self.sha1.to_s
    
    self.crc32.downcase!
    self.md5.downcase!
    self.sha1.downcase!
  end
end

app/models/media_type.rb
class MediaType < ActiveRecord::Base
  has_many :discs
  has_and_belongs_to_many :property_groups
  has_many :childs, :class_name => "MediaType", :foreign_key => "parent_id"
  belongs_to :parent, :class_name => "MediaType"
  
  attr_accessible :title, :abbreviation, :parent_id
  
  validates_length_of :title, :in => 1..255
  validates_length_of :abbreviation, :maximum => 255
  validate :parent_id do
    errors.add(:parent_id, "doesn't exist") if !self.parent_id.nil? and self.parent.nil?
  end
  
  before_save do
    self.abbreviation = self.abbreviation.to_s
  end
  
  def self.tree(elements = self.all, root = nil)
    tree = {}
    elements.select { |element| element.parent_id == root }.each do |element|
      tree[element] = tree(elements, element.id)
    end
    tree
  end
end

app/models/property.rb
class Property < ActiveRecord::Base
  belongs_to :property_group
  has_many :property_values
end

app/models/property_group.rb
class PropertyGroup < ActiveRecord::Base
  has_and_belongs_to_many :media_types
  has_many :properties
end

app/models/property_value.rb
class DiscsProperty < ActiveRecord::Base
  belongs_to :disc
  belongs_to :property
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  layout 'application'
end

app/controllers/discs_controller.rb
class DiscsController < ApplicationController
  def index
    @discs = Disc.all
  end

  def show
    @disc = Disc.find(params[:id])
  end

  def new
    @disc = Disc.new
  end

  def edit
    @disc = Disc.find(params[:id])
  end

  def create
    @disc = Disc.new(params[:disc])

    if @disc.save
      redirect_to(@disc, :notice => 'Disc was successfully created.')
    else
      render :action => "new"
    end
  end

  def update
    @disc = Disc.find(params[:id])

    if @disc.update_attributes(params[:disc])
      redirect_to(@disc, :notice => 'Disc was successfully updated.')
    else
      render :action => "edit"
    end
  end

  def destroy
    @disc = Disc.find(params[:id])
    @disc.destroy

    redirect_to(discs_url)
  end
end

app/controllers/media_types_controller.rb
class MediaTypesController < ApplicationController
  def index
    @media_types = MediaType.tree
  end

  def show
    @media_type = MediaType.find(params[:id])
  end

  def new
    @media_type = MediaType.new
    @media_types = MediaType.tree
    @property_groups = PropertyGroup.all
  end

  def edit
    @media_type = MediaType.find(params[:id])
    @media_types = MediaType.tree
    @property_groups = PropertyGroup.all
  end

  def create
    @media_type = MediaType.new(params[:media_type])

    if @media_type.save
      redirect_to(@media_type, :notice => 'Media type was successfully created.')
    else
      @media_types = MediaType.tree
      @property_groups = PropertyGroup.all
      render :action => "new"
    end
  end

  def update
    @media_type = MediaType.find(params[:id])

    if @media_type.update_attributes(params[:media_type])
      redirect_to(@media_type, :notice => 'Media type was successfully updated.')
    else
      @media_types = MediaType.tree
      @property_groups = PropertyGroup.all
      render :action => "edit"
    end
  end

  def destroy
    @media_type = MediaType.find(params[:id])
    @media_type.destroy

    redirect_to(media_types_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/discs_helper.rb
module DiscsHelper
  def status(disc)
    Disc.statuses[disc.status].to_s.humanize
  end
  
  def status_image(disc)
    raw '<img src="/images/status/' + Disc.statuses[disc.status].to_s + '.png" />'
  end
  
  def status_image_text(disc)
    status_image(disc) + ' ' + status(disc)
  end
end

app/helpers/media_types_helper.rb
module MediaTypesHelper
  def parent_options_tree(tree, current, tab = 1, include_blank = true)
    output = String.new
    output << "<option value=\"\">Disc</option>" if include_blank
    tree.each do |element, branch|
      next if current.id == element.id
      output << "<option value=\"#{element.id}\""
      output << " selected=\"selected\"" if current.parent_id == element.id
      output << ">"
      (tab*4).times { output << "&nbsp;" }
      output << h(element.title)
      output << "</option>"
      output << parent_options_tree(branch, current, tab+1, false) unless branch.blank?
    end
    output
  end
end

app/views/discs/_form.html.erb
<%= form_for(@disc) do |f| %>
  <% if @disc.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@disc.errors.count, "error") %> prohibited this disc from being saved:</h2>
    <ul>
    <% @disc.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  <div class="field">
    <%= f.label :comments %><br />
    <%= f.text_area :comments %>
  </div>
  <div class="field">
    <%= f.label :internal_date %><br />
    <%= f.text_field :internal_date %>
  </div>
  <div class="field">
    <%= f.label :internal_serial %><br />
    <%= f.text_field :internal_serial %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :subtitle %><br />
    <%= f.text_field :subtitle %>
  </div>
  <div class="field">
    <%= f.label :scene_filename %><br />
    <%= f.text_field :scene_filename %>
  </div>
  <div class="field">
    <%= f.label :filename %><br />
    <%= f.text_field :filename %>
  </div>
  <div class="field">
    <%= f.label :size %><br />
    <%= f.text_field :size %>
  </div>
  <div class="field">
    <%= f.label :crc32 %><br />
    <%= f.text_field :crc32 %>
  </div>
  <div class="field">
    <%= f.label :md5 %><br />
    <%= f.text_field :md5 %>
  </div>
  <div class="field">
    <%= f.label :sha1 %><br />
    <%= f.text_field :sha1 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/discs/edit.html.erb
<h1>Editing disc</h1>

<%= render 'form' %>

app/views/discs/index.html.erb
<h1>Listing discs</h1>

<%= link_to 'New disc', new_disc_path %>

<% if @discs.empty? %>
<p>No discs found.</p>
<% else %>  
<table>
  <tr>
    <th>Title</th>
    <th>Status</th>
    <th>Serial</th>
  </tr>

<% @discs.each do |disc| %>
  <tr>
    <td><%= link_to disc.title, disc %></td>
    <td><%= status_image disc %></td>
    <td><%= disc.internal_serial %></td>
  </tr>
<% end %>
</table>
<% end %>

app/views/discs/new.html.erb
<h1>New disc</h1>

<%= render 'form' %>

app/views/discs/show.html.erb
<p class="notice"><%= notice %></p>

<ul>
  <li><%= link_to 'Edit', edit_disc_path(@disc) %></li>
  <li><%= link_to 'Delete', @disc, :confirm => 'Are you sure?', :method => :delete %></li>
</ul>

<dl>
  <dt>Title:</dt>
  <dd><%= @disc.title %></dd>
  <% unless @disc.subtitle.blank? %>
  <dt>Subtitle:</dt>
  <dd><%= @disc.subtitle %></dd>  
  <% end %>
  <% unless @disc.internal_serial.blank? %>
  <dt>Internal serial:</dt>
  <dd><%= @disc.internal_serial %></dd>
  <% end %>
  <% unless @disc.internal_serial.blank? %>
  <dt>Internal date:</dt>
  <dd><%= @disc.internal_date %></dd>
  <% end %>
  <dt>Status:</dt>
  <dd><%= status_image_text @disc %></dd>
  <dt>Filename:</dt>
  <dd><%= @disc.scene_filename %></dd>
  <% unless @disc.crc32.blank? %>
  <dt>Scene filename:</dt>
  <dd><%= @disc.scene_filename %></dd>
  <% end %>
  <% unless @disc.comments.blank? %>
  <dt>Comments:</dt>
  <dd><%= @disc.comments %></dd>
  <% end %>
  <% unless @disc.size.blank? %>
  <dt>Size:</dt>
  <dd><%= @disc.size %></dd>
  <% end %>
  <% unless @disc.crc32.blank? %>
  <dt>CRC-32:</dt>
  <dd><%= @disc.crc32 %></dd>
  <% end %>
  <% unless @disc.md5.blank? %>
  <dt>MD5:</dt>
  <dd><%= @disc.md5 %></dd>
  <% end %>
  <% unless @disc.sha1.blank? %>
  <dt>SHA-1:</dt>
  <dd><%= @disc.sha1 %></dd>
  <% end %>
  <dt>Created:</dt>
  <dd><%= @disc.created_at %></dd>
  <dt>Updated:</dt>
  <dd><%= @disc.updated_at %></dd>
</dl>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Redump</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/media_types/_branch.html.erb
<ul>
<% branch.each do |k, v| %>
<li><%= link_to k.title, k %></li>
<%= render :partial => "branch", :locals => { :branch => v } unless v.blank? %>
<% end %>
</ul>

app/views/media_types/_form.html.erb
<%= form_for(@media_type) do |f| %>
  <% if @media_type.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@media_type.errors.count, "error") %> prohibited this Media type from being saved:</h2>
    <ul>
    <% @media_type.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :abbreviation %><br />
    <%= f.text_field :abbreviation %>
  </div>
  <div class="field">
    <%= f.label :parent_id %><br />
    <%= f.select :parent_id, parent_options_tree(@media_types, @media_type) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/media_types/edit.html.erb
<h1>Editing Media type</h1>

<%= render 'form' %>

<%= link_to 'Show', @media_type %> |
<%= link_to 'Back', media_types_path %>

app/views/media_types/index.html.erb
<h1>Listing Media types</h1>

<%= render :partial => "branch", :locals => { :branch => @media_types } %>

<br />

<%= link_to 'New Media type', new_media_type_path %>

app/views/media_types/new.html.erb
<h1>New Media type</h1>

<%= render 'form' %>

<%= link_to 'Back', media_types_path %>

app/views/media_types/show.html.erb
<p class="notice"><%= notice %></p>

<dl>
	<dt>Title:</dt>
	<dd><%= @media_type.title %></dd>
	
	<% unless @media_type.abbreviation.blank? %>
	<dt>Abbreviation:</dt>
	<dd><%= @media_type.abbreviation %></dd>
	<% end %>

	<% unless @media_type.parent_id.nil? %>
	<dt>Parent:</dt>
	<dd><%= link_to @media_type.parent.title, @media_type.parent %></dd>
	<% end %>

	<% unless @media_type.childs.blank? %>
	<dt>Childs:</dt>
	<dd>
		<ul>
			<% @media_type.childs.each do |child| %>
			<li><%= link_to child.title, child %></li>
			<% end %>
		</ul>
	</dd>
	<% end %>
</dl>

<%= link_to 'Edit', edit_media_type_path(@media_type) %> |
<%= link_to 'Back', media_types_path %>